import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { App, ConfigProvider, Layout } from "antd";

import StyledComponentsRegistry from "../../lib/AntdRegistry";

import "./globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Электронный журнал оператора",
  description: "Generated by create next app",
  icons:  "https://cdn.freebiesupply.com/logos/large/2x/OAO-logo-black-and-white.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <App className="w-full h-full flex flex-row">
          <StyledComponentsRegistry>
            <ConfigProvider>{children}</ConfigProvider>
          </StyledComponentsRegistry>
        </App>
      </body>
    </html>
  );
}
